from oldowan.mtconvert.seq2sites import seq2sites
from oldowan.polymorphism import Polymorphism

def test_29InsATTCTCTGTTCTTT():
    """Properly identify 16029InsATTCTCTGTTCTTT

    Seq:  GATTCTAATTTAAACTATTCTCTGTTCTTTATTCTCTGTTCTTTCATGGGGAAGCAGATTTGGGT

    Seq:  GATTCTAATTTAAACTATTCTCTGTTCTTTATTCTCTGTTCTTTCATGGGGAAGCAGATTTGGGT
    rCRS: GATTCTAATTTAAACTATTCTCTGTTCTTT--------------CATGGGGAAGCAGATTTGGGT

    Sites: <None>
    """
    seq = 'GATTCTAATTTAAACTATTCTCTGTTCTTTATTCTCTGTTCTTTCATGGGGAAGCAGATTTGGGT'
    result = seq2sites(seq)
    assert len(result) == 14
